"""
Universal file edit-session workflow on top of :class:`CodeAnalysisAsyncClient`.

Wraps ``universal_file_open`` / ``edit`` / ``write`` / ``close`` / ``preview`` only.
Legacy ``universal_file_read`` / ``universal_file_save`` and CST commands are not
part of this API (see :mod:`server_api`).

Author: Vasiliy Zdanovskiy
email: vasilyvz@gmail.com
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Dict, List, Optional

from ai_editor_client.responses import unwrap_command_result

if TYPE_CHECKING:
    from ai_editor_client.client import CodeAnalysisAsyncClient


class UniversalFileClient:
    """Edit-session workflow for project files (open → edit → write → close).

    ``session_id`` is the CA Session identifier (C-004): the agent creates it on
    upstream and passes the same value into every workflow call (C-003). It is
    not generated by ``open`` and is not the legacy client ``session_*`` API
    (``session_create``, ``session_open_file``, …).
    """

    __slots__ = ("_client",)

    def __init__(self, client: CodeAnalysisAsyncClient) -> None:
        self._client = client

    async def open(
        self,
        project_id: str,
        file_path: str,
        session_id: str,
        *,
        create: bool = False,
        initial_content: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Start File Workflow open stage (C-009) via universal_file_open (C-016).

        Identifies the file by ``project_id`` + ``file_path`` (not ``file_id``).
        """
        params: Dict[str, Any] = {
            "project_id": project_id,
            "file_path": file_path,
            "session_id": session_id,
            "create": create,
        }
        if initial_content is not None:
            params["initial_content"] = initial_content
        return unwrap_command_result(
            await self._client.call_validated("universal_file_open", params)
        )

    async def edit(
        self,
        project_id: str,
        session_id: str,
        operations: List[Dict[str, Any]],
        *,
        file_path: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Apply edit stage mutations (C-009) via universal_file_edit (C-016)."""
        params: Dict[str, Any] = {
            "project_id": project_id,
            "session_id": session_id,
            "operations": operations,
        }
        if file_path is not None:
            params["file_path"] = file_path
        return unwrap_command_result(
            await self._client.call_validated("universal_file_edit", params)
        )

    async def write(
        self,
        project_id: str,
        session_id: str,
        *,
        file_path: Optional[str] = None,
        write_mode: str = "commit",
    ) -> Dict[str, Any]:
        """Run write stage (C-009) via universal_file_write (C-016).

        Default ``write_mode`` is ``commit`` in this client wrapper. The server
        default when the parameter is omitted is ``preview``. Pass
        ``write_mode='preview'`` first to inspect the diff, then ``commit``.
        """
        params: Dict[str, Any] = {
            "project_id": project_id,
            "session_id": session_id,
            "write_mode": write_mode,
        }
        if file_path is not None:
            params["file_path"] = file_path
        return unwrap_command_result(
            await self._client.call_validated("universal_file_write", params)
        )

    async def close(
        self,
        project_id: str,
        session_id: str,
        *,
        file_path: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Run close stage (C-009) via universal_file_close (C-016)."""
        params: Dict[str, Any] = {
            "project_id": project_id,
            "session_id": session_id,
        }
        if file_path is not None:
            params["file_path"] = file_path
        return unwrap_command_result(
            await self._client.call_validated("universal_file_close", params)
        )

    async def preview(
        self,
        project_id: str,
        file_path: str,
        session_id: str,
        **kwargs: Any,
    ) -> Dict[str, Any]:
        """Read-only preview via universal_file_preview (C-016)."""
        params: Dict[str, Any] = {
            "project_id": project_id,
            "file_path": file_path,
            "session_id": session_id,
        }
        params.update(kwargs)
        return unwrap_command_result(
            await self._client.call_validated("universal_file_preview", params)
        )
