"""
Metadata for universal_file_open command (AI/docs).

Author: Vasiliy Zdanovskiy
email: vasilyvz@gmail.com
"""

from __future__ import annotations

from typing import Any, Dict, Type

from ai_editor.commands.universal_file_edit.workflow_brief import WORKFLOW_STEPS_TEXT


def get_universal_file_open_metadata(cls: Type[Any]) -> Dict[str, Any]:
    """Return command metadata dict for universal_file_open.

    Args:
        cls: The command class (UniversalFileOpenCommand).

    Returns:
        Metadata dict with description, parameters, examples, errors.
    """
    return {
        "name": cls.name,
        "version": cls.version,
        "description": cls.descr,
        "category": cls.category,
        "author": cls.author,
        "email": cls.email,
        "detailed_description": (
            "Open Stage (C-010): lock a project file on Code Analysis Server (CA), "
            "download bytes into the editor workspace, and start an in-memory edit "
            "session for that file.\n\n"
            "**CA session_id (required):** The agent must obtain `session_id` from "
            "CA `session_create` upstream and pass the same id on every "
            "universal_file_* call. It is the CA session identifier — not an optional "
            "editor group id and not generated by this command.\n\n"
            "**Upstream lock + download (inside open):** This command performs CA "
            "orchestration internally; do not call separate MCP session_open_file or "
            "download commands. When create=False, the server calls "
            "lock_file_and_download (session_open_file lock, then chunked download). "
            "When create=True, it calls upload_create_and_lock (upload, save, lock).\n\n"
            "File identity: project_id + project-relative file_path (no file_id in "
            "the MCP request).\n\n"
            "Workspace layout: under configured workspace_root, files for one CA "
            "session live under `{workspace_root}/{session_id}/`. The success "
            "response includes session_dir (Editor Session Directory) and draft_path "
            "(draft copy under the file's Edit Subdirectory).\n\n"
            f"{WORKFLOW_STEPS_TEXT}\n"
            "Multi-file: the same CA session_id may open multiple files; "
            "multi_file_bundle and repeat_open describe the bundle state.\n\n"
            "Parse-error fallback: when a structured file cannot be parsed, the session "
            "opens in line-based fallback instead of failing. The response includes "
            "is_invalid, fallback_reason, warning, and mode_notice.\n"
            "After fixing syntax and committing, structural editing is restored "
            "automatically.\n\n"
            "After open, call universal_file_preview for node_ref values: marked-tree "
            "formats return integer short_id; invalid sessions use line pagination only."
        ),
        "parameters": {
            "project_id": {
                "description": (
                    "Project UUID. Resolves the project root on disk and CA project "
                    "context. Use list_projects to discover valid values."
                ),
                "type": "string",
                "required": True,
                "examples": ["8772a086-688d-4198-a0c4-f03817cc0e6c"],
            },
            "file_path": {
                "description": (
                    "Project-relative path to the file to open. Literal path; no globs."
                ),
                "type": "string",
                "required": True,
                "examples": [
                    "ai_editor/commands/my_command.py",
                    "config/settings.yaml",
                ],
            },
            "session_id": {
                "description": (
                    "CA session id (required). Same id returned by CA session_create; "
                    "mandatory CA Session context (C-004). Pass on every open — not an "
                    "optional editor group id. Reused across universal_file_open, "
                    "preview, edit, write, and close for the same editing context."
                ),
                "type": "string",
                "required": True,
                "examples": ["a1b2c3d4-e5f6-7890-abcd-ef1234567890"],
            },
            "create": {
                "description": (
                    "When True, create the file on Code Analysis Server if it does not "
                    "exist (upload_create_and_lock branch). "
                    "For .py files, initial_content is required. "
                    "For JSON/YAML, initial_content is written as raw text when "
                    "provided; otherwise an empty object {} is written. "
                    "For text formats, an empty file is created."
                ),
                "type": "boolean",
                "required": False,
                "default": False,
            },
            "initial_content": {
                "description": (
                    "Initial content for new files (create=True only). "
                    "For .py: required; uploaded to CA, then CST tree is built in "
                    "workspace. "
                    "For .json: written as-is when non-empty, else `{}\\n`. "
                    "For .yaml/.yml: written as-is when non-empty (with YAML quoting "
                    "fixups), else `{}\\n`. Invalid JSON/YAML opens in text fallback "
                    "with is_invalid. "
                    "For other text extensions: written as-is when non-empty, else "
                    "empty file."
                ),
                "type": "string",
                "required": False,
            },
            "format_group": {
                "description": (
                    "Explicit format group override. Applied only when the file "
                    "extension is unknown or absent (e.g. Makefile, .env, .sh). "
                    "Ignored when the extension is already recognised by the handler "
                    "registry. "
                    "Valid values: "
                    "sidecar — Python CST structural editing; "
                    "tree-temp — JSON/YAML tree editing; "
                    "text — plain line-based editing. "
                    "When omitted and the extension is unknown, the command returns "
                    "UNKNOWN_FORMAT."
                ),
                "type": "string",
                "required": False,
                "enum": ["sidecar", "tree-temp", "text"],
            },
        },
        "return_value": {
            "success": {
                "description": (
                    "File locked on CA, copied into workspace; draft session ready."
                ),
                "data": {
                    "session_id": (
                        "CA session id (echo of input); use on subsequent "
                        "universal_file_* calls."
                    ),
                    "file_path": "Project-relative path of the opened file.",
                    "format_group": (
                        "Handler routing group: sidecar, tree-temp, or text."
                    ),
                    "session_dir": (
                        "Absolute Editor Session Directory: "
                        "{workspace_root}/{session_id}/."
                    ),
                    "draft_path": (
                        "Absolute path to the in-session draft copy under the file's "
                        "Edit Subdirectory."
                    ),
                    "available_operations": (
                        "Supported operation types: insert, delete, replace."
                    ),
                    "created": (
                        "True when create=True and the file did not exist (optional)."
                    ),
                    "repeat_open": (
                        "True when this CA session already had at least one open file "
                        "before this call (optional)."
                    ),
                    "multi_file_bundle": (
                        "Bundle summary for the CA session (always present): "
                        "session_id, open_file_count, and files list with file_path, "
                        "project_id, origin_path, draft_path, edit_subdir per entry."
                    ),
                    "fallback_reason": (
                        "Parse error message when structured parse failed and "
                        "line-based fallback was used (optional)."
                    ),
                    "is_invalid": (
                        "True when the file has syntax errors and the session opened "
                        "in line-based fallback (optional)."
                    ),
                    "warning": (
                        "Human-readable explanation when is_invalid is True (optional)."
                    ),
                    "mode_notice": (
                        "Human-readable note about structural vs text fallback mode "
                        "(optional)."
                    ),
                },
                "example": {
                    "session_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                    "file_path": "config/settings.yaml",
                    "format_group": "tree-temp",
                    "session_dir": "/var/editor-workspace/a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                    "draft_path": (
                        "/var/editor-workspace/a1b2c3d4-e5f6-7890-abcd-ef1234567890/"
                        "8772a086-688d-4198-a0c4-f03817cc0e6c/config/settings.yaml/"
                        "edit-1/draft/settings.yaml"
                    ),
                    "available_operations": ["insert", "delete", "replace"],
                    "repeat_open": False,
                },
            },
            "error": {
                "description": "Session could not be opened.",
                "code": "Stable error code (see error_cases).",
                "message": "Human-readable description.",
            },
        },
        "usage_examples": [
            {
                "description": "Open an existing YAML config file for editing",
                "command": {
                    "project_id": "8772a086-688d-4198-a0c4-f03817cc0e6c",
                    "file_path": "config/settings.yaml",
                    "session_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                },
                "explanation": (
                    "Agent supplies CA session_id from session_create. Open locks and "
                    "downloads the file, returns session_dir and draft_path. Run "
                    "universal_file_preview next for node_ref values."
                ),
            },
            {
                "description": "Create a new Python module",
                "command": {
                    "project_id": "8772a086-688d-4198-a0c4-f03817cc0e6c",
                    "file_path": "ai_editor/commands/my_new_command.py",
                    "session_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                    "create": True,
                    "initial_content": (
                        "'''\nMy new command.\n'''\n\nfrom __future__ import annotations\n"
                    ),
                },
                "explanation": (
                    "create=True uploads initial_content to CA and locks the new file. "
                    "Run universal_file_preview before editing."
                ),
            },
        ],
        "error_cases": {
            "SESSION_NOT_FOUND": {
                "description": (
                    "CA session_id is unknown or invalid on Code Analysis Server "
                    "(Session Guard reject), or the in-memory editor bundle has no "
                    "entry for this session_id after server restart."
                ),
                "message": "CA session not found or invalid: {session_id}",
                "solution": (
                    "Create a new CA session via session_create upstream and retry "
                    "open with the new session_id."
                ),
            },
            "SESSION_INVALID": {
                "description": (
                    "session_id is missing or empty after parameter normalization."
                ),
                "message": "session_id is required for universal_file_open",
                "solution": (
                    "Pass a non-empty CA session_id obtained from session_create."
                ),
            },
            "FILE_ALREADY_OPEN": {
                "description": (
                    "The same project file is already open in another CA session bundle, "
                    "or the file is already open under this session_id."
                ),
                "message": "File already open in session {session_id}: {file_path}",
                "solution": (
                    "Close the owning universal_file_close session for that file, "
                    "or use a different file_path, and retry."
                ),
            },
            "PARSE_ERROR": {
                "description": (
                    "Unrecoverable parse error at open when text fallback is not used."
                ),
                "message": "Cannot parse file: {exc}",
                "solution": (
                    "Fix syntax errors in the file. For .py/.json/.yaml, text-mode "
                    "fallback is used when possible (is_invalid in success response)."
                ),
            },
            "OPEN_ERROR": {
                "description": (
                    "Upstream CA lock or download failed: file not found in project "
                    "(create=False), CA lock held by another session, transfer error, "
                    "or other RuntimeError from lock_file_and_download / "
                    "upload_create_and_lock."
                ),
                "message": "{upstream RuntimeError message}",
                "solution": (
                    "Verify file_path exists in the project (or pass create=True), "
                    "ensure no other CA session holds the lock, and retry."
                ),
            },
            "VALIDATION_ERROR": {
                "description": (
                    "Parameter validation failed (e.g. empty session_id caught in "
                    "validate_params)."
                ),
                "message": "{ValidationError message}",
                "solution": "Fix parameters per get_schema() and retry.",
            },
            "UNKNOWN_FORMAT": {
                "description": (
                    "File extension not supported by any handler, and no valid "
                    "format_group hint was supplied."
                ),
                "message": "Unsupported file type: {suffix}",
                "solution": (
                    "Either use a supported extension (.py, .json, .yaml, .yml, "
                    ".md, .txt, .toml, .ini, .cfg) or pass format_group with one "
                    "of: sidecar, tree-temp, text to force a handler for files "
                    "with unknown or absent extensions."
                ),
            },
        },
        "best_practices": [
            "Obtain session_id from CA session_create before the first universal_file_open.",
            "Reuse the same session_id for open, preview, edit, write, and close.",
            "Do not call separate MCP session_open_file or download — open handles upstream lock+download.",
            "Always call universal_file_close when done to unlock on CA and free workspace memory.",
            "Always call universal_file_preview after open to obtain node_ref values for edits.",
            "If is_invalid is True, fix parse errors and commit before expecting node-based edits.",
            "One open file per (project_id, file_path) at a time — a second open returns FILE_ALREADY_OPEN.",
        ],
    }
