"""Common-model-to-LibCST export pipeline for the Python translator (C-014).

Scope (concept C-014, narrowed to the EXPORT direction only): this module is
the exact inverse of the merged ``import_map.py``. It converts a common-model
tree (:class:`~tree_engine.core.nodes.Node` / ``Document``) that was built by
(or shaped exactly like) ``PythonImportMap.import_to_common`` back into a
*temporary* LibCST tree, then runs LibCST's own code generation to produce
source bytes in the encoding preserved on the common model. It also exposes
``export_tree``, the export side of the ``import_tree``/``export_tree``
bridge {p048} for callers that want the reconstructed LibCST object itself
(the "LibCST-compatible subset") rather than generated bytes.

Translation strategy -- generic, mirroring the importer exactly: every
common-model ``Node`` whose ``kind`` is ``"python:<LibCST class name>"`` is
rebuilt by looking up that class on the installed ``libcst`` module and
calling it with keyword arguments built from ``Node.fields``, one entry per
LibCST dataclass field -- no hand-maintained per-node-kind table, so the
mapping can never drift from the importer's. The two marker kinds the
importer introduced are decoded back into the exact values LibCST expects:

* ``"python:$sentinel"`` (only ever ``libcst.MaybeSentinel.DEFAULT`` in this
  LibCST version, per the importer's own docstring) is resolved back to the
  named ``enum.Enum`` member, importing whatever module the marker recorded
  rather than hard-coding ``MaybeSentinel`` -- symmetric with the importer's
  own generic (not per-node-kind) treatment of enum values.
* ``"python:$scalar"`` unwraps back to the bare primitive it wrapped, for a
  primitive that appeared as an element of a ``Sequence``/``tuple`` field.

A common-model ``Node`` whose ``kind`` names no attribute of ``libcst`` at
all has no mappable LibCST equivalent and raises
:class:`~tree_engine.plugins.contract.UnsupportedTranslationError` (carrying
``ErrorCode.UNSUPPORTED_TRANSLATION`` from ``src/tree_engine/errors.py``),
identifying the offending node kind -- never guessed, approximated, or
silently dropped. A recognized kind whose stored fields do not satisfy that
LibCST class's own constructor (a shape mismatch, not a missing mapping) is a
different failure and raises
:class:`~tree_engine.plugins.contract.FormatPluginContractError` instead, the
same distinction the importer draws between "cannot represent" and "not a
CSTNode at all".

Byte ranges ({p102}) are metadata the importer attached to
``Node.buffer_range`` for addressing/query purposes; LibCST's code generator
never consumes stored byte offsets, only trivia/whitespace/comment fields
(which are ordinary ``Node.fields`` entries here, exactly as the importer
left them), so an unchanged document reproduces its own byte ranges for free
by reproducing its own bytes -- this module has nothing extra to "replay"
for them. Likewise ``encoding``, ``default_indent``, ``default_newline``,
``has_trailing_newline``, ``header``, and ``footer`` need no side-channel:
they are simply ``"python:Module"``'s own ``fields`` entries, restored by
the same generic field-by-field reconstruction as every other node.

A full document (a common-model ``Document`` whose ``root`` is a
``"python:Module"`` node) is rebuilt into a real ``libcst.Module`` and
rendered via its own ``.bytes`` property (``code_for_node(self).encode(self.encoding)``),
so the preserved encoding is exactly what produces the final bytes. A bare
fragment ``Node`` is rebuilt into whatever ``CSTNode`` its kind names and
rendered via ``libcst.Module(body=[]).code_for_node(fragment)`` -- the
documented way to render an arbitrary ``CSTNode`` without a real enclosing
module -- returning ``str`` rather than ``bytes`` since a fragment carries no
preserved encoding of its own.

Every LibCST object this module constructs is local to one
``export_from_common``/``export_tree`` call: ``export_from_common`` returns
only ``bytes``/``str`` and retains no reference to the tree it built once it
returns, so nothing keeps that temporary tree alive afterward (including on
the ``UnsupportedTranslationError``/``FormatPluginContractError`` paths,
which unwind without stashing anything in module- or instance-level state).
``export_tree`` is the one deliberate exception: per its bridge contract it
returns the rebuilt LibCST object itself to the caller, exactly as
``import_tree`` accepts one -- the caller, not this module, owns it from
that point on.

``PythonExportMap`` is not itself a complete
:class:`~tree_engine.plugins.contract.FormatPluginContract` implementation
-- it supplies that contract's export stage only, the sibling counterpart of
``PythonImportMap``; a later step composes both into the full plugin.

Source-of-truth requirement labels honored here: {p008}, {p022}, {p048},
{p049}, {p102}.
"""

from __future__ import annotations

import importlib
from typing import Any, Dict, Mapping, Optional, Union

import libcst

from tree_engine.core.nodes import Document, FieldValue, Node
from tree_engine.plugins.contract import FormatPluginContractError, UnsupportedTranslationError

__all__ = [
    "FORMAT_ID",
    "PythonExportMap",
    "export_tree",
]

FORMAT_ID = "python"

_KIND_PREFIX = "python:"
_SENTINEL_KIND = f"{_KIND_PREFIX}$sentinel"
_SCALAR_KIND = f"{_KIND_PREFIX}$scalar"


def _contract_error(message: str) -> FormatPluginContractError:
    return FormatPluginContractError(plugin_id=FORMAT_ID, message=message)


def _unsupported(node_kind: str, message: str = "") -> UnsupportedTranslationError:
    return UnsupportedTranslationError(node_type=node_kind, format_id=FORMAT_ID, message=message)


def _resolve_enum_member(enum_class_path: str, member_name: str) -> Any:
    """Resolve a ``"$sentinel"`` marker's ``enum_class``/``member`` pair
    back to the live ``enum.Enum`` member, generically -- not hard-coded to
    ``MaybeSentinel`` -- by importing progressively shorter module-name
    prefixes of the dotted path until one imports successfully, then
    walking any remaining dotted attribute(s) off of it. Mirrors the
    importer's own generic (not per-enum-kind) treatment of enum values."""

    parts = enum_class_path.split(".")
    for split in range(len(parts), 0, -1):
        module_name = ".".join(parts[:split])
        try:
            module = importlib.import_module(module_name)
        except ImportError:
            continue
        target: Any = module
        try:
            for attr in parts[split:]:
                target = getattr(target, attr)
        except AttributeError:
            continue
        if isinstance(target, type):
            return getattr(target, member_name)
    raise _contract_error(
        f"cannot resolve enum class {enum_class_path!r} recorded on a "
        "'$sentinel' marker node"
    )


def _rebuild_node(node: Node) -> Any:
    """Rebuild one common-model ``Node`` back into whatever LibCST-side
    value it represents: a decoded enum member for a ``"$sentinel"``
    marker, the unwrapped primitive for a ``"$scalar"`` marker, or a real
    ``libcst.CSTNode`` for every other (``"python:<ClassName>"``) kind."""

    if not isinstance(node, Node):
        raise _contract_error(f"expected a Node, got {type(node).__name__}")

    if node.kind == _SENTINEL_KIND:
        enum_class_path = node.fields.get("enum_class")
        member_name = node.fields.get("member")
        if not isinstance(enum_class_path, str) or not isinstance(member_name, str):
            raise _contract_error(
                "malformed '$sentinel' marker node: expected string "
                "'enum_class' and 'member' fields"
            )
        return _resolve_enum_member(enum_class_path, member_name)

    if node.kind == _SCALAR_KIND:
        if "value" not in node.fields:
            raise _contract_error("malformed '$scalar' marker node: missing 'value' field")
        return node.fields["value"]

    if not node.kind.startswith(_KIND_PREFIX):
        raise _unsupported(str(node.kind), f"node kind {node.kind!r} is not a Python plugin kind")

    class_name = str(node.kind)[len(_KIND_PREFIX):]
    cst_cls = getattr(libcst, class_name, None)
    if cst_cls is None or not isinstance(cst_cls, type) or not issubclass(cst_cls, libcst.CSTNode):
        raise _unsupported(
            str(node.kind),
            f"no libcst.{class_name} class exists; this common-model node "
            "kind has no mappable LibCST equivalent",
        )

    kwargs: Dict[str, Any] = {}
    for field_name, field_value in node.fields.items():
        kwargs[field_name] = _rebuild_field_value(field_value)

    try:
        return cst_cls(**kwargs)
    except TypeError as exc:
        raise _contract_error(
            f"stored fields of node kind {node.kind!r} do not satisfy "
            f"libcst.{class_name}'s constructor: {exc}"
        ) from exc


def _rebuild_field_value(value: FieldValue) -> Any:
    """Inverse of the importer's ``_convert_value``: a primitive passes
    through unchanged, a single ``Node`` is rebuilt via ``_rebuild_node``
    (decoding a marker or reconstructing a real ``CSTNode``), and a tuple
    is rebuilt element-wise the same way, in order."""

    if value is None or isinstance(value, (str, int, float, bool, bytes)):
        return value
    if isinstance(value, Node):
        return _rebuild_node(value)
    if isinstance(value, tuple):
        return [_rebuild_node(item) for item in value]
    raise _contract_error(
        f"unexpected common-model field value type {type(value).__name__}; "
        "expected a primitive, a Node, or a tuple of Node"
    )


def _rebuild(common_tree: Union[Node, Document]) -> Any:
    """Rebuild the temporary LibCST object for either a full ``Document``
    (root must reconstruct into a ``libcst.Module``) or a bare fragment
    ``Node`` (reconstructs into whatever ``CSTNode`` its kind names)."""

    if isinstance(common_tree, Document):
        rebuilt = _rebuild_node(common_tree.root)
        if not isinstance(rebuilt, libcst.Module):
            raise _contract_error(
                "Document.root did not reconstruct into a libcst.Module "
                f"(got {type(rebuilt).__name__}); a Document's root must be "
                "a 'python:Module' node"
            )
        return rebuilt
    if isinstance(common_tree, Node):
        return _rebuild_node(common_tree)
    raise _contract_error(
        f"expected a common-model Node or Document, got {type(common_tree).__name__}"
    )


def _generate(rebuilt: Any) -> Union[bytes, str]:
    """Run LibCST's own code generation over an already-rebuilt temporary
    tree. A ``libcst.Module`` renders to ``bytes`` via its own ``.bytes``
    property, which encodes ``code_for_node(self)`` using the module's own
    preserved ``encoding`` -- exactly the preserved-encoding byte output
    this step requires. Any other ``CSTNode`` (a fragment) has no encoding
    of its own, so it renders to ``str`` via an empty scratch
    ``libcst.Module``'s ``code_for_node`` -- LibCST's documented way to
    render an arbitrary node without a real enclosing module."""

    if isinstance(rebuilt, libcst.Module):
        return rebuilt.bytes
    if isinstance(rebuilt, libcst.CSTNode):
        return libcst.Module(body=[]).code_for_node(rebuilt)
    raise _contract_error(
        f"rebuilt value is not a libcst.CSTNode (got {type(rebuilt).__name__}); "
        "cannot generate output"
    )


class PythonExportMap:
    """Export (common model -> LibCST -> bytes/str) stage of the Python
    translator.

    Supplies the export half of the bidirectional translator described by
    ``tree_engine.plugins.contract.FormatPluginContract`` ({p056}, {p057});
    the import stage is delivered by the sibling, already-merged
    ``PythonImportMap``, and the remaining contract surface (``metadata``,
    ``parse_document``, ...) is composed later.
    """

    def export_from_common(
        self,
        common_tree: Union[Node, Document],
        options: Optional[Mapping[str, Any]] = None,
    ) -> Union[bytes, str]:
        """Translate a common-model ``Document``/``Node`` back into source
        output: ``bytes`` (in the encoding preserved on the ``Document``)
        for a full document, or ``str`` for a bare fragment ``Node``.
        ``options`` is accepted for contract-signature compatibility and
        currently unused by the export path itself.

        Raises :class:`~tree_engine.plugins.contract.UnsupportedTranslationError`
        for a common-model node kind with no mappable LibCST equivalent, and
        :class:`~tree_engine.plugins.contract.FormatPluginContractError` for
        any other export-side contract violation (malformed marker data, a
        recognized kind whose fields do not satisfy its LibCST
        constructor, or a non-Module ``Document.root``). No LibCST object
        is retained after this call returns, on either the success or the
        error path.
        """

        rebuilt = _rebuild(common_tree)
        return _generate(rebuilt)


def export_tree(
    common_tree: Union[Node, Document],
    *,
    options: Optional[Mapping[str, Any]] = None,
) -> Any:
    """Export side of the ``import_tree``/``export_tree`` bridge {p048}:
    rebuilds and returns the temporary LibCST object itself (a
    ``libcst.Module`` for a ``Document``, or the appropriate ``CSTNode``
    for a fragment ``Node``) for a caller that wants the LibCST-compatible
    object rather than generated bytes/str -- the exact inverse of
    ``import_tree`` accepting an already-parsed LibCST object. Unlike
    :meth:`PythonExportMap.export_from_common`, the rebuilt object is
    deliberately handed back here rather than discarded: from this point
    on the caller, not this module, owns it.

    Raises the same :class:`~tree_engine.plugins.contract.UnsupportedTranslationError`/
    :class:`~tree_engine.plugins.contract.FormatPluginContractError` as
    :meth:`PythonExportMap.export_from_common` for the same reasons.
    """

    return _rebuild(common_tree)
